# Generated by Django 3.0.3 on 2020-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='author/profile'),
        ),
    ]
