# Generated by Django 3.0.3 on 2020-04-06 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200405_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
    ]
